# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_turns', models.IntegerField()),
                ('disable_turns', models.IntegerField(default=False)),
                ('taken_turns', models.IntegerField()),
                ('untaken_turns', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('available', models.BooleanField(default=True)),
                ('taken_by', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_days', models.IntegerField()),
            ],
        ),
    ]
